mvc/mvc1/mvc1/Models/ErrorViewModel.cs
using System;

namespace mvc1.Models
{
   public class ErrorViewModel
   {
      public string RequestId { get; set; }

      public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
   }
}

mvc/mvc1/mvc1/Models/Skier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace mvc1.Models
{
   public class Skier
   {
      [Key]
      public int Id { get; set; }
      [Required]
      [Column(TypeName ="nvarchar(20)")]
      public string Name { get; set; }
      [DisplayName("Skier #")]
      [Required]
      [Range(1,int.MaxValue,ErrorMessage ="Skier Number must be greater than 0")]
      public int SkierNumber { get; set; }
      [Required]
      public bool IsSlalom { get; set; }
      [Required]
      public bool IsTrick { get; set; }
      [Column("IsJ")]
      [Required]
      public bool IsJump { get; set; }
      [Required]
      [DisplayName("Salary Cap")]
      public int SalaryCap { get; set; }
      [DisplayName("Betting Line")]
      public double BettingLine { get; set; }
      [NotMapped]
      public DateTime LoadedFromDatabase { get; set; }
      public DateTime Birthday { get; set; }
   }
}

mvc/mvc1/mvc1/Models/Tourney.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mvc1.Models
{
   public class Tourney
   {
      [Key]
      public int Id { get; set; }
      [Required]
      public string Name { get; set; }
      [Required]
      [DisplayName("Tourney #")]
      [Range(1, int.MaxValue, ErrorMessage = "Tourney Number must be greater than 0")]
      public int TourneyNumber { get; set; }
   }
}

mvc/mvc1/mvc1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc1.Models;

namespace mvc1.Controllers
{
   public class HomeController : Controller
   {
      private readonly ILogger<HomeController> _logger;

      public HomeController(ILogger<HomeController> logger)
      {
         _logger = logger;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult Privacy()
      {
         return View();
      }

      [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }
   }
}

mvc/mvc1/mvc1/Controllers/SkierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc1.Data;
using mvc1.Models;

namespace mvc1.Controllers
{
    public class SkierController : Controller
    {
      private readonly ApplicationDbContext _db;

      public SkierController(ApplicationDbContext db)
      {
         _db = db;
      }
        public IActionResult Index()
        {
         IEnumerable<Skier> skierList = _db.Skier;
            return View(skierList);
        }

      // GET - CREATE
      public IActionResult Create()
      {
         return View();
      }

      //POST - CREATE
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult Create(Skier obj)
      {
         if (ModelState.IsValid)
         {
            _db.Skier.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(obj);

      }

      // GET - EDIT
      public IActionResult Edit(int? id)
      {
         if (id == null || id == 0)
         {
            return NotFound();
         }
         var obj = _db.Skier.Find(id); // .Find() ==> PK
         if (obj == null)
         {
            return NotFound();
         }
         return View(obj);
      }

      //POST - EDIT
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult Edit(Skier obj)
      {
         if (ModelState.IsValid)
         {
            _db.Skier.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(obj);

      }

      // GET - DELETE
      public IActionResult Delete(int? id)
      {
         if (id == null || id == 0)
         {
            return NotFound();
         }
         var obj = _db.Skier.Find(id); // .Find() ==> PK
         if (obj == null)
         {
            return NotFound();
         }
         return View(obj);
      }

      //POST - DELETE
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult DeletePost(int? id)
      {
         var obj = _db.Skier.Find(id);
         if (obj == null)
         {
            return NotFound();
         }
         _db.Skier.Remove(obj);
         _db.SaveChanges();
         return RedirectToAction("Index");

      }
   }
}

mvc/mvc1/mvc1/Controllers/TourneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc1.Data;
using mvc1.Models;

namespace mvc1.Controllers
{
   public class TourneyController : Controller
   {
      private readonly ApplicationDbContext _db;

      public TourneyController(ApplicationDbContext db)
      {
         _db = db;
      }
      public IActionResult Index()
      {
         IEnumerable<Tourney> tourneyList = _db.Tourney;
         return View(tourneyList);
      }

      // GET - CREATE
      public IActionResult Create()
      {
         return View();
      }

      //POST - CREATE
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult Create(Tourney obj)
      {
         if (ModelState.IsValid)
         {
            _db.Tourney.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(obj);

      }

      // GET - EDIT
      public IActionResult Edit(int? id)
      {
         if (id == null || id == 0)
         {
            return NotFound();
         }
         var obj = _db.Tourney.Find(id); // .Find() ==> PK
         if (obj == null)
         {
            return NotFound();
         }
         return View(obj);
      }

      //POST - EDIT
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult Edit(Tourney obj)
      {
         if (ModelState.IsValid)
         {
            _db.Tourney.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(obj);

      }

      // GET - DELETE
      public IActionResult Delete(int? id)
      {
         if (id == null || id == 0)
         {
            return NotFound();
         }
         var obj = _db.Tourney.Find(id); // .Find() ==> PK
         if (obj == null)
         {
            return NotFound();
         }
         return View(obj);
      }

      //POST - DELETE
      [HttpPost]
      [ValidateAntiForgeryToken]
      public IActionResult DeletePost(int? id)
      {
         var obj = _db.Tourney.Find(id);
         if (obj == null)
         {
            return NotFound();
         }
         _db.Tourney.Remove(obj);
         _db.SaveChanges();
         return RedirectToAction("Index");

      }
   }
}

mvc/mvc1/mvc1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc/mvc1/mvc1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - mvc1</title>
   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   <link rel="stylesheet" href="~/css/site.css" />
   <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                   <ul class="navbar-nav flex-grow-1">
                      <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                      </li>
                      <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                      </li>
                      <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Skier" asp-action="Index">Skier</a>
                      </li>
                      <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Tourney" asp-action="Index">Tourney</a>
                      </li>
                   </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mvc1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

mvc/mvc1/mvc1/Views/Skier/Create.cshtml
@model mvc1.Models.Skier

<form method="post" asp-action="Create">
   <div class="border p-3">
      @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
      <div class="form-group row">
         <h2 class="text-info pl-3">Add Skier</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" class="form-control" />
                  <span asp-validation-for="Name" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="SkierNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="SkierNumber" class="form-control" />
                  <span asp-validation-for="SkierNumber" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-info w-100" value="Create" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

@section Scripts{

   @{
      <partial name="_ValidationScriptsPartial" />
   }

}

mvc/mvc1/mvc1/Views/Skier/Delete.cshtml
@model mvc1.Models.Skier

<form method="post" asp-action="DeletePost">
   <input asp-for="Id" hidden />
   <div class="border p-3">
      <div class="form-group row">
         <h2 class="text-info pl-3">Delete Skier</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" disabled class="form-control" />
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="SkierNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="SkierNumber" disabled class="form-control" />
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-danger w-100" value="Delete" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

@section Scripts{

   @{
      <partial name="_ValidationScriptsPartial" />
   }

}

mvc/mvc1/mvc1/Views/Skier/Edit.cshtml
@model mvc1.Models.Skier

<form method="post">
   <input asp-for="Id" hidden />
   <div class="border p-3">
      <div class="form-group row">
         <h2 class="text-info pl-3">Edit Skier</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" class="form-control" />
                  <span asp-validation-for="Name" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="SkierNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="SkierNumber" class="form-control" />
                  <span asp-validation-for="SkierNumber" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-info w-100" value="Update" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

@section Scripts{

   @{
      <partial name="_ValidationScriptsPartial" />
   }

}

mvc/mvc1/mvc1/Views/Skier/Index.cshtml
@model IEnumerable<mvc1.Models.Skier>


<div class="container p-3">
   <div class="row pt-4">
      <div class="col-6">
         <h2>Skier List</h2>
      </div>
      <div class="col-6">
         <a asp-controller="Skier" asp-action="Create" class="btn btn-primary">
            <i class="fas fa-plus"></i> New Skier
         </a>
      </div>
   </div>
   <br />
   @if (Model.Count() > 0)
   {
      <table class="table table-bordered table-striped" style="width:100%">
         <thead>
            <tr>
               <th>
                  Skier Name
               </th>
               <th>
                  Skier Number (not id)
               </th>
            </tr>
         </thead>
         <tbody>
            @foreach(var skier in Model)
            {
            <tr>
               <td width="50%">@skier.Name</td>
               <td width="30%">@skier.SkierNumber</td>
               <td class="text-center">
                  <div class="w-75 btn-group" role="group">
                     <a asp-controller="Skier" asp-route-Id="@skier.Id" asp-action="Edit" class="btn btn-primary mx-2">
                        <i class="fas fa-edit"></i>
                     </a>
                     <a asp-controller="Skier" asp-route-Id="@skier.Id" asp-action="Delete" class="btn btn-danger mx-2">
                        <i class="far fa-trash-alt"></i>
                     </a>
                  </div>
               </td>
            </tr>
            }
         </tbody>
      </table> 
   }
   else
   {
      <p>no skiers found.</p>
   }
</div>



mvc/mvc1/mvc1/Views/Tourney/Create.cshtml
@model mvc1.Models.Tourney

<form method="post" asp-action="Create">
   <div class="border p-3">
      @*<div asp-validation-summary="All" class="text-danger"></div>
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
      <div class="form-group row">
         <h2 class="text-info pl-3">Add Tourney</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" class="form-control" />
                  <span asp-validation-for="Name" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="TourneyNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="TourneyNumber" class="form-control" />
                  <span asp-validation-for="TourneyNumber" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-info w-100" value="Create" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

mvc/mvc1/mvc1/Views/Tourney/Delete.cshtml
@model mvc1.Models.Tourney

<form method="post" asp-action="DeletePost">
   <input asp-for="Id" hidden />
   <div class="border p-3">
      <div class="form-group row">
         <h2 class="text-info pl-3">Delete Tourney</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" disabled class="form-control" />
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="TourneyNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="TourneyNumber" disabled class="form-control" />
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-danger w-100" value="Delete" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

@section Scripts{

   @{
      <partial name="_ValidationScriptsPartial" />
   }

}

mvc/mvc1/mvc1/Views/Tourney/Edit.cshtml
@model mvc1.Models.Tourney

<form method="post">
   <input asp-for="Id" hidden />
   <div class="border p-3">
      <div class="form-group row">
         <h2 class="text-info pl-3">Edit Tourney</h2>
      </div>
      <div class="row">
         <div class="col-8">
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="Name"></label>
               </div>
               <div class="col-8">
                  <input asp-for="Name" class="form-control" />
                  <span asp-validation-for="Name" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-4">
                  <label asp-for="TourneyNumber"></label>
               </div>
               <div class="col-8">
                  <input asp-for="TourneyNumber" class="form-control" />
                  <span asp-validation-for="TourneyNumber" class="text-danger"></span>
               </div>

            </div>
            <div class="form-group row">
               <div class="col-8 offset-4 row">

                  <div class="col">
                     <input type="submit" class="btn btn-info w-100" value="Update" />
                  </div>
                  <div class="col">
                     <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-4">
            @* Keep this empty *@
         </div>
      </div>
   </div>

</form>

@section Scripts{

   @{
      <partial name="_ValidationScriptsPartial" />
   }

}

mvc/mvc1/mvc1/Views/Tourney/Index.cshtml
@model IEnumerable<mvc1.Models.Tourney>


<div class="container p-3">
   <div class="row pt-4">
      <div class="col-6">
         <h2>Tourney List</h2>
      </div>
      <div class="col-6">
         <a asp-controller="Tourney" asp-action="Create" class="btn btn-primary">
            <i class="fas fa-plus"></i> New Tourney
         </a>
      </div>
   </div>
   <br />
   @if (Model.Count() > 0)
   {
      <table class="table table-bordered table-striped" style="width:100%">
         <thead>
            <tr>
               <th>
                  Tourney Name
               </th>
               <th>
                  Tourney Number (not id)
               </th>
            </tr>
         </thead>
         <tbody>
            @foreach(var tourney in Model)
            {
            <tr>
               <td width="50%">@tourney.Name</td>
               <td width="30%">@tourney.TourneyNumber</td>
               <td class="text-center">
                  <div class="w-75 btn-group" role="group">
                     <a asp-controller="Tourney" asp-route-Id="@tourney.Id" asp-action="Edit" class="btn btn-primary mx-2">
                        <i class="fas fa-edit"></i>
                     </a>
                     <a asp-controller="Tourney" asp-route-Id="@tourney.Id" asp-action="Delete" class="btn btn-danger mx-2">
                        <i class="far fa-trash-alt"></i>
                     </a>
                  </div>
               </td>
            </tr>
            }
         </tbody>
      </table> 
   }
   else
   {
      <p>no tourneys found.</p>
   }
</div>

